export const CREATE_PROJECT = '@@project/CREATE_PROJECT';
export const CREATE_PROJECT_START = '@@project/CREATE_PROJECT_START';
export const CREATE_PROJECT_SUCCESS = '@@project/CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILED = '@@project/CREATE_PROJECT_FAILED';
export const PROJECT_ADD_RESET = '@@project/PROJECT_ADD_RESET';
