export const AUTHENTICATE = '@@login/AUTHENTICATE';
export const AUTHENTICATE_START = '@@login/AUTHENTICATE_START';
export const AUTHENTICATE_SUCCESS = '@@login/AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILED = '@@login/AUTHENTICATE_FAILED';
export const LOGIN_RESET = '@@login/LOGIN_RESET';
