export const API_URL = process.env.REACT_APP_API_URL
export const AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY"

export const INITIAL = "INITIAL"
export const READY = "READY"
export const SUBMITTED = "SUBMITTED"

export const LOGIN_SUBMIT = 'LOGIN_SUBMIT'
export const LOGIN_SUBMIT_START = 'LOGIN_SUBMIT_START'
export const LOGIN_SUBMIT_DONE = 'LOGIN_SUBMIT_END'

export const PROJECT_PAGE_GET_INIT_DATA = 'PROJECT_PAGE_GET_INIT_DATA'
export const PROJECT_PAGE_GET_INIT_DATA_START = 'PROJECT_PAGE_GET_INIT_DATA_START'
export const PROJECT_PAGE_GET_INIT_DATA_SUCCESS = 'PROJECT_PAGE_GET_INIT_DATA_SUCCESS'
export const PROJECT_PAGE_GET_INIT_DATA_FAILED = 'PROJECT_PAGE_GET_INIT_DATA_FAILED'

export const PROJECT_PAGE_GET_DATA = 'PROJECT_PAGE_GET_DATA'
export const PROJECT_PAGE_GET_DATA_START = 'PROJECT_PAGE_GET_DATA_START'
export const PROJECT_PAGE_GET_DATA_SUCCESS = 'PROJECT_PAGE_GET_DATA_SUCCESS'
export const PROJECT_PAGE_GET_DATA_FAILED = 'PROJECT_PAGE_GET_DATA_FAILED'

